name: synheart_wear
description: Unified wearable SDK for Synheart (HR, HRV, steps, energy, stress).
version: 0.1.0
homepage: https://github.com/synheart-ai/synheart_wear

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  collection: ^1.18.0
  uuid: ^4.4.0
  path_provider: ^2.1.4
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SynheartWearPlugin