name: synheart_wear
description: Unified wearable SDK for Synheart (HR, HRV, steps, energy, stress).
version: 0.1.0
homepage: https://github.com/synheart-ai/synheart_wear
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  collection: ^1.18.0
  uuid: ^4.4.0
  path_provider: ^2.1.4
  health: ^10.0.0
  platform: ^3.1.6
  # Platform bridges (add as needed)
  # health: ^9.0.0
  # google_fit: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
flutter:
  plugin:
    platforms:
      android:
        package: ai.synheart.wear
        pluginClass: SynheartWearPlugin
      ios:
        pluginClass: SynheartWearPlugin
